apiVersion: v1
kind: Service
metadata:
  name: llmops-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: llmops-app
  ports:
    - name: http
      protocol: TCP
      port: 80          # service port
      targetPort: 8501  # containerPort in your Deployment
      nodePort: 30080   # choose an open NodePort (30000–32767)
